// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/BorisBorshevsky/timemock (interfaces: Clock)

package mock_timemock

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
	time "time"
)

// MockClock is a mock of Clock interface
type MockClock struct {
	ctrl     *gomock.Controller
	recorder *MockClockMockRecorder
}

// MockClockMockRecorder is the mock recorder for MockClock
type MockClockMockRecorder struct {
	mock *MockClock
}

// NewMockClock creates a new mock instance
func NewMockClock(ctrl *gomock.Controller) *MockClock {
	mock := &MockClock{ctrl: ctrl}
	mock.recorder = &MockClockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockClock) EXPECT() *MockClockMockRecorder {
	return _m.recorder
}

// Freeze mocks base method
func (_m *MockClock) Freeze(_param0 time.Time) {
	_m.ctrl.Call(_m, "Freeze", _param0)
}

// Freeze indicates an expected call of Freeze
func (_mr *MockClockMockRecorder) Freeze(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Freeze", reflect.TypeOf((*MockClock)(nil).Freeze), arg0)
}

// Now mocks base method
func (_m *MockClock) Now() time.Time {
	ret := _m.ctrl.Call(_m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now
func (_mr *MockClockMockRecorder) Now() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Now", reflect.TypeOf((*MockClock)(nil).Now))
}

// Return mocks base method
func (_m *MockClock) Return() {
	_m.ctrl.Call(_m, "Return")
}

// Return indicates an expected call of Return
func (_mr *MockClockMockRecorder) Return() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Return", reflect.TypeOf((*MockClock)(nil).Return))
}

// Scale mocks base method
func (_m *MockClock) Scale(_param0 float64) {
	_m.ctrl.Call(_m, "Scale", _param0)
}

// Scale indicates an expected call of Scale
func (_mr *MockClockMockRecorder) Scale(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Scale", reflect.TypeOf((*MockClock)(nil).Scale), arg0)
}

// Since mocks base method
func (_m *MockClock) Since(_param0 time.Time) time.Duration {
	ret := _m.ctrl.Call(_m, "Since", _param0)
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// Since indicates an expected call of Since
func (_mr *MockClockMockRecorder) Since(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Since", reflect.TypeOf((*MockClock)(nil).Since), arg0)
}

// Travel mocks base method
func (_m *MockClock) Travel(_param0 time.Time) {
	_m.ctrl.Call(_m, "Travel", _param0)
}

// Travel indicates an expected call of Travel
func (_mr *MockClockMockRecorder) Travel(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Travel", reflect.TypeOf((*MockClock)(nil).Travel), arg0)
}
