// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/BorisBorshevsky/timemock (interfaces: Clock)

// Package mock_timemock is a generated GoMock package.
package mock_timemock

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
	time "time"
)

// MockClock is a mock of Clock interface
type MockClock struct {
	ctrl     *gomock.Controller
	recorder *MockClockMockRecorder
}

// MockClockMockRecorder is the mock recorder for MockClock
type MockClockMockRecorder struct {
	mock *MockClock
}

// NewMockClock creates a new mock instance
func NewMockClock(ctrl *gomock.Controller) *MockClock {
	mock := &MockClock{ctrl: ctrl}
	mock.recorder = &MockClockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockClock) EXPECT() *MockClockMockRecorder {
	return m.recorder
}

// Freeze mocks base method
func (m *MockClock) Freeze(arg0 time.Time) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Freeze", arg0)
}

// Freeze indicates an expected call of Freeze
func (mr *MockClockMockRecorder) Freeze(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Freeze", reflect.TypeOf((*MockClock)(nil).Freeze), arg0)
}

// Now mocks base method
func (m *MockClock) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now
func (mr *MockClockMockRecorder) Now() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*MockClock)(nil).Now))
}

// Return mocks base method
func (m *MockClock) Return() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Return")
}

// Return indicates an expected call of Return
func (mr *MockClockMockRecorder) Return() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Return", reflect.TypeOf((*MockClock)(nil).Return))
}

// Scale mocks base method
func (m *MockClock) Scale(arg0 float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Scale", arg0)
}

// Scale indicates an expected call of Scale
func (mr *MockClockMockRecorder) Scale(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scale", reflect.TypeOf((*MockClock)(nil).Scale), arg0)
}

// Since mocks base method
func (m *MockClock) Since(arg0 time.Time) time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Since", arg0)
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// Since indicates an expected call of Since
func (mr *MockClockMockRecorder) Since(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Since", reflect.TypeOf((*MockClock)(nil).Since), arg0)
}

// Travel mocks base method
func (m *MockClock) Travel(arg0 time.Time) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Travel", arg0)
}

// Travel indicates an expected call of Travel
func (mr *MockClockMockRecorder) Travel(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Travel", reflect.TypeOf((*MockClock)(nil).Travel), arg0)
}

// Until mocks base method
func (m *MockClock) Until(arg0 time.Time) time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Until", arg0)
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// Until indicates an expected call of Until
func (mr *MockClockMockRecorder) Until(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Until", reflect.TypeOf((*MockClock)(nil).Until), arg0)
}
